name: Build Android APK (Direct Docker Method)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Docker-Image Pull mit Cache
      - name: Cache Docker Image
        uses: actions/cache@v4
        with:
          path: /tmp/.docker-cache
          key: kivy-buildozer-latest

      - name: Pull Kivy Buildozer Docker Image
        run: |
          mkdir -p /tmp/.docker-cache
          if ! docker image inspect kivy/buildozer:latest > /dev/null 2>&1; then
            docker pull kivy/buildozer:latest
          fi

      - name: Build with Buildozer using Docker
        run: |
          set -e
          docker run --rm \
            -v "$(pwd)":/home/user/app \
            kivy/buildozer:latest \
            buildozer -v android debug

      - name: Check for APK
        run: |
          if ! ls bin/*.apk 1> /dev/null 2>&1; then
            echo "Keine APK gefunden! Build fehlgeschlagen."
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: voicecloningapp-apk
          path: bin/*.apk
